# Dockerfile.dev

FROM node:22-alpine
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose default Next.js dev port
EXPOSE 3000

# Start in development mode
CMD ["npm", "run", "dev"]
