on: 
  push:
    branches:
      - nextjs-mongodb
name: 🚀 Deploy website on push
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: 🧰 Install dependencies
        run: npm install

      - name: 🏗️ Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.URL }}
          NEXTAUTH_ACCESSTOKEN: ${{ secrets.TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXTAUTH_SECRET: ${{ secrets.TOKEN }}
          NEXTAUTH_URL: ${{ secrets.URL }}
          CRYPTO_SECRET_KEY: ${{ secrets.CRYPTO_SECRET_KEY }}
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SESSION_STRATEGY: ${{ secrets.SESSION_STRATEGY }}
          SESSION_MAXAGE: ${{ secrets.SESSION_MAXAGE }}
          SESSION_UPDATEAGE: ${{ secrets.SESSION_UPDATEAGE }}

      - name: 🚀 Upload .next folder to cPanel via FTP
        run: node scripts/deploy-production.js
        env:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
