on: 
  push:
    branches:
      - nextjs-mongodb
name: 🚀 Deploy website on push
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🧰 Install dependencies
        run: npm install

      - name: 🏗️ Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.URL }}
          NEXTAUTH_ACCESSTOKEN: ${{ secrets.TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXTAUTH_SECRET: ${{ secrets.TOKEN }}
          NEXTAUTH_URL: ${{ secrets.URL }}
          CRYPTO_SECRET_KEY: ${{ secrets.CRYPTO_SECRET_KEY }}
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SESSION_STRATEGY: ${{ secrets.SESSION_STRATEGY }}
          SESSION_MAXAGE: ${{ secrets.SESSION_MAXAGE }}
          SESSION_UPDATEAGE: ${{ secrets.SESSION_UPDATEAGE }}

      # 8️⃣ Deploy to your server via rsync
      - name: 📂 Upload files via rsync
        uses: Burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --exclude='.git*'
          path: "./"
          remote_path: ${{ secrets.TARGET }}
          remote_host: ${{ secrets.SERVER }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: 22
